from django.contrib.gis.db import models


class AggByCountyTA(models.Model):
    county = models.CharField(max_length=100)
    year = models.IntegerField(null=True)
    regular_pay_min = models.FloatField(null=True)
    regular_pay_max = models.FloatField(null=True)
    regular_pay_mean = models.FloatField(null=True)
    regular_pay_sum = models.FloatField(null=True)
    overtime_pay_min = models.FloatField(null=True)
    overtime_pay_max = models.FloatField(null=True)
    overtime_pay_mean = models.FloatField(null=True)
    overtime_pay_sum = models.FloatField(null=True)
    other_pay_min = models.FloatField(null=True)
    other_pay_max = models.FloatField(null=True)
    other_pay_mean = models.FloatField(null=True)
    other_pay_sum = models.FloatField(null=True)
    total_pay_min = models.FloatField(null=True)
    total_pay_max = models.FloatField(null=True)
    total_pay_mean = models.FloatField(null=True)
    total_pay_sum = models.FloatField(null=True)
    benefits_min = models.FloatField(null=True)
    benefits_max = models.FloatField(null=True)
    benefits_mean = models.FloatField(null=True)
    benefits_sum = models.FloatField(null=True)
    total_pay_and_benefits_min = models.FloatField(null=True)
    total_pay_and_benefits_max = models.FloatField(null=True)
    total_pay_and_benefits_mean = models.FloatField(null=True)
    total_pay_and_benefits_sum = models.FloatField(null=True)


class AggByDistrictTA(models.Model):
    county = models.CharField(max_length=100)
    district = models.CharField(max_length=100)
    year = models.IntegerField(null=True)
    regular_pay_min = models.FloatField(null=True)
    regular_pay_max = models.FloatField(null=True)
    regular_pay_mean = models.FloatField(null=True)
    regular_pay_sum = models.FloatField(null=True)
    overtime_pay_min = models.FloatField(null=True)
    overtime_pay_max = models.FloatField(null=True)
    overtime_pay_mean = models.FloatField(null=True)
    overtime_pay_sum = models.FloatField(null=True)
    other_pay_min = models.FloatField(null=True)
    other_pay_max = models.FloatField(null=True)
    other_pay_mean = models.FloatField(null=True)
    other_pay_sum = models.FloatField(null=True)
    total_pay_min = models.FloatField(null=True)
    total_pay_max = models.FloatField(null=True)
    total_pay_mean = models.FloatField(null=True)
    total_pay_sum = models.FloatField(null=True)
    benefits_min = models.FloatField(null=True)
    benefits_max = models.FloatField(null=True)
    benefits_mean = models.FloatField(null=True)
    benefits_sum = models.FloatField(null=True)
    total_pay_and_benefits_min = models.FloatField(null=True)
    total_pay_and_benefits_max = models.FloatField(null=True)
    total_pay_and_benefits_mean = models.FloatField(null=True)
    total_pay_and_benefits_sum = models.FloatField(null=True)


class AggByCountyT(models.Model):
    county = models.CharField(max_length=100)
    year = models.IntegerField(null=True)
    regular_pay_min = models.FloatField(null=True)
    regular_pay_max = models.FloatField(null=True)
    regular_pay_mean = models.FloatField(null=True)
    regular_pay_sum = models.FloatField(null=True)
    overtime_pay_min = models.FloatField(null=True)
    overtime_pay_max = models.FloatField(null=True)
    overtime_pay_mean = models.FloatField(null=True)
    overtime_pay_sum = models.FloatField(null=True)
    other_pay_min = models.FloatField(null=True)
    other_pay_max = models.FloatField(null=True)
    other_pay_mean = models.FloatField(null=True)
    other_pay_sum = models.FloatField(null=True)
    total_pay_min = models.FloatField(null=True)
    total_pay_max = models.FloatField(null=True)
    total_pay_mean = models.FloatField(null=True)
    total_pay_sum = models.FloatField(null=True)
    benefits_min = models.FloatField(null=True)
    benefits_max = models.FloatField(null=True)
    benefits_mean = models.FloatField(null=True)
    benefits_sum = models.FloatField(null=True)
    total_pay_and_benefits_min = models.FloatField(null=True)
    total_pay_and_benefits_max = models.FloatField(null=True)
    total_pay_and_benefits_mean = models.FloatField(null=True)
    total_pay_and_benefits_sum = models.FloatField(null=True)


class AggByDistrictT(models.Model):
    county = models.CharField(max_length=100)
    district = models.CharField(max_length=100)
    year = models.IntegerField(null=True)
    regular_pay_min = models.FloatField(null=True)
    regular_pay_max = models.FloatField(null=True)
    regular_pay_mean = models.FloatField(null=True)
    regular_pay_sum = models.FloatField(null=True)
    overtime_pay_min = models.FloatField(null=True)
    overtime_pay_max = models.FloatField(null=True)
    overtime_pay_mean = models.FloatField(null=True)
    overtime_pay_sum = models.FloatField(null=True)
    other_pay_min = models.FloatField(null=True)
    other_pay_max = models.FloatField(null=True)
    other_pay_mean = models.FloatField(null=True)
    other_pay_sum = models.FloatField(null=True)
    total_pay_min = models.FloatField(null=True)
    total_pay_max = models.FloatField(null=True)
    total_pay_mean = models.FloatField(null=True)
    total_pay_sum = models.FloatField(null=True)
    benefits_min = models.FloatField(null=True)
    benefits_max = models.FloatField(null=True)
    benefits_mean = models.FloatField(null=True)
    benefits_sum = models.FloatField(null=True)
    total_pay_and_benefits_min = models.FloatField(null=True)
    total_pay_and_benefits_max = models.FloatField(null=True)
    total_pay_and_benefits_mean = models.FloatField(null=True)
    total_pay_and_benefits_sum = models.FloatField(null=True)


class AggByCountyA(models.Model):
    county = models.CharField(max_length=100)
    year = models.IntegerField(null=True)
    regular_pay_min = models.FloatField(null=True)
    regular_pay_max = models.FloatField(null=True)
    regular_pay_mean = models.FloatField(null=True)
    regular_pay_sum = models.FloatField(null=True)
    overtime_pay_min = models.FloatField(null=True)
    overtime_pay_max = models.FloatField(null=True)
    overtime_pay_mean = models.FloatField(null=True)
    overtime_pay_sum = models.FloatField(null=True)
    other_pay_min = models.FloatField(null=True)
    other_pay_max = models.FloatField(null=True)
    other_pay_mean = models.FloatField(null=True)
    other_pay_sum = models.FloatField(null=True)
    total_pay_min = models.FloatField(null=True)
    total_pay_max = models.FloatField(null=True)
    total_pay_mean = models.FloatField(null=True)
    total_pay_sum = models.FloatField(null=True)
    benefits_min = models.FloatField(null=True)
    benefits_max = models.FloatField(null=True)
    benefits_mean = models.FloatField(null=True)
    benefits_sum = models.FloatField(null=True)
    total_pay_and_benefits_min = models.FloatField(null=True)
    total_pay_and_benefits_max = models.FloatField(null=True)
    total_pay_and_benefits_mean = models.FloatField(null=True)
    total_pay_and_benefits_sum = models.FloatField(null=True)


class AggByDistrictA(models.Model):
    county = models.CharField(max_length=100)
    district = models.CharField(max_length=100)
    year = models.IntegerField(null=True)
    regular_pay_min = models.FloatField(null=True)
    regular_pay_max = models.FloatField(null=True)
    regular_pay_mean = models.FloatField(null=True)
    regular_pay_sum = models.FloatField(null=True)
    overtime_pay_min = models.FloatField(null=True)
    overtime_pay_max = models.FloatField(null=True)
    overtime_pay_mean = models.FloatField(null=True)
    overtime_pay_sum = models.FloatField(null=True)
    other_pay_min = models.FloatField(null=True)
    other_pay_max = models.FloatField(null=True)
    other_pay_mean = models.FloatField(null=True)
    other_pay_sum = models.FloatField(null=True)
    total_pay_min = models.FloatField(null=True)
    total_pay_max = models.FloatField(null=True)
    total_pay_mean = models.FloatField(null=True)
    total_pay_sum = models.FloatField(null=True)
    benefits_min = models.FloatField(null=True)
    benefits_max = models.FloatField(null=True)
    benefits_mean = models.FloatField(null=True)
    benefits_sum = models.FloatField(null=True)
    total_pay_and_benefits_min = models.FloatField(null=True)
    total_pay_and_benefits_max = models.FloatField(null=True)
    total_pay_and_benefits_mean = models.FloatField(null=True)
    total_pay_and_benefits_sum = models.FloatField(null=True)


class AggByCountyS(models.Model):
    county = models.CharField(max_length=100)
    year = models.IntegerField(null=True)
    regular_pay_min = models.FloatField(null=True)
    regular_pay_max = models.FloatField(null=True)
    regular_pay_mean = models.FloatField(null=True)
    regular_pay_sum = models.FloatField(null=True)
    overtime_pay_min = models.FloatField(null=True)
    overtime_pay_max = models.FloatField(null=True)
    overtime_pay_mean = models.FloatField(null=True)
    overtime_pay_sum = models.FloatField(null=True)
    other_pay_min = models.FloatField(null=True)
    other_pay_max = models.FloatField(null=True)
    other_pay_mean = models.FloatField(null=True)
    other_pay_sum = models.FloatField(null=True)
    total_pay_min = models.FloatField(null=True)
    total_pay_max = models.FloatField(null=True)
    total_pay_mean = models.FloatField(null=True)
    total_pay_sum = models.FloatField(null=True)
    benefits_min = models.FloatField(null=True)
    benefits_max = models.FloatField(null=True)
    benefits_mean = models.FloatField(null=True)
    benefits_sum = models.FloatField(null=True)
    total_pay_and_benefits_min = models.FloatField(null=True)
    total_pay_and_benefits_max = models.FloatField(null=True)
    total_pay_and_benefits_mean = models.FloatField(null=True)
    total_pay_and_benefits_sum = models.FloatField(null=True)


class AggByDistrictS(models.Model):
    county = models.CharField(max_length=100)
    district = models.CharField(max_length=100)
    year = models.IntegerField(null=True)
    regular_pay_min = models.FloatField(null=True)
    regular_pay_max = models.FloatField(null=True)
    regular_pay_mean = models.FloatField(null=True)
    regular_pay_sum = models.FloatField(null=True)
    overtime_pay_min = models.FloatField(null=True)
    overtime_pay_max = models.FloatField(null=True)
    overtime_pay_mean = models.FloatField(null=True)
    overtime_pay_sum = models.FloatField(null=True)
    other_pay_min = models.FloatField(null=True)
    other_pay_max = models.FloatField(null=True)
    other_pay_mean = models.FloatField(null=True)
    other_pay_sum = models.FloatField(null=True)
    total_pay_min = models.FloatField(null=True)
    total_pay_max = models.FloatField(null=True)
    total_pay_mean = models.FloatField(null=True)
    total_pay_sum = models.FloatField(null=True)
    benefits_min = models.FloatField(null=True)
    benefits_max = models.FloatField(null=True)
    benefits_mean = models.FloatField(null=True)
    benefits_sum = models.FloatField(null=True)
    total_pay_and_benefits_min = models.FloatField(null=True)
    total_pay_and_benefits_max = models.FloatField(null=True)
    total_pay_and_benefits_mean = models.FloatField(null=True)
    total_pay_and_benefits_sum = models.FloatField(null=True)


class AggByCountyTAS(models.Model):
    county = models.CharField(max_length=100)
    year = models.IntegerField(null=True)
    regular_pay_min = models.FloatField(null=True)
    regular_pay_max = models.FloatField(null=True)
    regular_pay_mean = models.FloatField(null=True)
    regular_pay_sum = models.FloatField(null=True)
    overtime_pay_min = models.FloatField(null=True)
    overtime_pay_max = models.FloatField(null=True)
    overtime_pay_mean = models.FloatField(null=True)
    overtime_pay_sum = models.FloatField(null=True)
    other_pay_min = models.FloatField(null=True)
    other_pay_max = models.FloatField(null=True)
    other_pay_mean = models.FloatField(null=True)
    other_pay_sum = models.FloatField(null=True)
    total_pay_min = models.FloatField(null=True)
    total_pay_max = models.FloatField(null=True)
    total_pay_mean = models.FloatField(null=True)
    total_pay_sum = models.FloatField(null=True)
    benefits_min = models.FloatField(null=True)
    benefits_max = models.FloatField(null=True)
    benefits_mean = models.FloatField(null=True)
    benefits_sum = models.FloatField(null=True)
    total_pay_and_benefits_min = models.FloatField(null=True)
    total_pay_and_benefits_max = models.FloatField(null=True)
    total_pay_and_benefits_mean = models.FloatField(null=True)
    total_pay_and_benefits_sum = models.FloatField(null=True)


class AggByDistrictTAS(models.Model):
    county = models.CharField(max_length=100)
    district = models.CharField(max_length=100)
    year = models.IntegerField(null=True)
    regular_pay_min = models.FloatField(null=True)
    regular_pay_max = models.FloatField(null=True)
    regular_pay_mean = models.FloatField(null=True)
    regular_pay_sum = models.FloatField(null=True)
    overtime_pay_min = models.FloatField(null=True)
    overtime_pay_max = models.FloatField(null=True)
    overtime_pay_mean = models.FloatField(null=True)
    overtime_pay_sum = models.FloatField(null=True)
    other_pay_min = models.FloatField(null=True)
    other_pay_max = models.FloatField(null=True)
    other_pay_mean = models.FloatField(null=True)
    other_pay_sum = models.FloatField(null=True)
    total_pay_min = models.FloatField(null=True)
    total_pay_max = models.FloatField(null=True)
    total_pay_mean = models.FloatField(null=True)
    total_pay_sum = models.FloatField(null=True)
    benefits_min = models.FloatField(null=True)
    benefits_max = models.FloatField(null=True)
    benefits_mean = models.FloatField(null=True)
    benefits_sum = models.FloatField(null=True)
    total_pay_and_benefits_min = models.FloatField(null=True)
    total_pay_and_benefits_max = models.FloatField(null=True)
    total_pay_and_benefits_mean = models.FloatField(null=True)
    total_pay_and_benefits_sum = models.FloatField(null=True)


class County(models.Model):
    county = models.CharField(max_length=100)
    geometry = models.MultiPolygonField(srid=4326)


class SchoolDistrict(models.Model):
    geoid = models.IntegerField(null=True)
    county = models.CharField(max_length=100, null=True)
    district = models.CharField(max_length=100, null=True)
    year = models.IntegerField(null=True)
    grade_low  = models.CharField(max_length=50)
    grade_high = models.CharField(max_length=50)
    geometry = models.MultiPolygonField(srid=4326)


class ELAMathTestScore(models.Model):
    county_code = models.IntegerField(null=True)
    district_code = models.IntegerField(null=True)
    school_code = models.IntegerField(null=True)
    cds_code = models.CharField(max_length=50, null=True)
    county = models.CharField(max_length=100, null=True)
    district = models.CharField(max_length=100, null=True)
    year = models.IntegerField(null=True)
    student_group_name = models.CharField(max_length=50, null=True)
    grade = models.CharField(null=True, max_length=10)
    test_name = models.CharField(max_length=50, null=True)
    mean_scale_score = models.FloatField(null=True)
    percentage_met_above = models.FloatField(null=True)
    percentage_nearly_met = models.FloatField(null=True)


class ScienceTestScore(models.Model):
    county_code = models.IntegerField(null=True)
    district_code = models.IntegerField(null=True)
    school_code = models.IntegerField(null=True)
    cds_code = models.CharField(max_length=50, null=True)
    county = models.CharField(max_length=100, null=True)
    district = models.CharField(max_length=100, null=True)
    year = models.IntegerField(null=True)
    student_group_name = models.CharField(max_length=50, null=True)
    grade = models.CharField(null=True, max_length=10)
    test_name = models.CharField(max_length=50, null=True)
    mean_scale_score = models.FloatField(null=True)
    percentage_met_above = models.FloatField(null=True)
    percentage_nearly_met = models.FloatField(null=True)