# Generated by Django 6.0.5 on 2026-08-02 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AllItems",
            fields=[
                ("name", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=50, null=True)),
                ("level", models.IntegerField(null=True)),
                ("rarity", models.IntegerField(null=True)),
                ("vendor_value", models.IntegerField(null=True)),
                ("default_skin", models.IntegerField(max_length=150, null=True)),
                ("game_types", models.JSONField(null=True)),
                ("flags", models.JSONField(null=True)),
                ("restrictions", models.JSONField(null=True)),
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("chat_link", models.CharField(max_length=20, null=True)),
                ("icon", models.CharField(max_length=100, null=True)),
                ("details", models.JSONField(null=True)),
                ("description", models.CharField(max_length=200, null=True)),
                ("upgrades_from", models.CharField(max_length=50, null=True)),
                ("upgrades_into", models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
