# Generated by Django 6.0.5 on 2026-08-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GW2Predict", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allitems",
            name="upgrades_from",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="allitems",
            name="upgrades_into",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
