# Generated by Django 6.0.5 on 2026-08-02 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GW2Predict", "0002_alter_allitems_upgrades_from_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allitems",
            name="chat_link",
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="allitems",
            name="default_skin",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="allitems",
            name="description",
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="allitems",
            name="details",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="allitems",
            name="flags",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="allitems",
            name="game_types",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="allitems",
            name="icon",
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="allitems",
            name="name",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="allitems",
            name="restrictions",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="allitems",
            name="type",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="allitems",
            name="upgrades_from",
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="allitems",
            name="upgrades_into",
            field=models.TextField(max_length=100, null=True),
        ),
    ]
