# Generated by Django 6.0.5 on 2026-08-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "GW2Predict",
            "0003_alter_allitems_chat_link_alter_allitems_default_skin_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="allitems",
            name="rarity",
            field=models.TextField(null=True),
        ),
    ]
