# Generated by Django 6.0.5 on 2026-05-24 06:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="County",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("county", models.CharField(max_length=100)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ELAMathTestScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("county_code", models.IntegerField(null=True)),
                ("district_code", models.IntegerField(null=True)),
                ("district_name", models.CharField(max_length=100, null=True)),
                ("school_code", models.IntegerField(null=True)),
                ("school_name", models.CharField(max_length=100, null=True)),
                ("student_group_id", models.IntegerField(null=True)),
                ("total_enrollment", models.IntegerField(null=True)),
                ("total_tested", models.IntegerField(null=True)),
                ("total_tested_with_scores", models.IntegerField(null=True)),
                ("total_enrollment_with_scores", models.IntegerField(null=True)),
                ("mean_scale_score", models.FloatField(null=True)),
                ("percentage_met_above", models.FloatField(null=True)),
                ("count_met_above", models.IntegerField(null=True)),
                ("percentage_nearly_met", models.FloatField(null=True)),
                ("count_nearly_met", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ELATestScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("county_code", models.IntegerField(null=True)),
                ("district_code", models.IntegerField(null=True)),
                ("district_name", models.CharField(max_length=100, null=True)),
                ("school_code", models.IntegerField(null=True)),
                ("school_name", models.CharField(max_length=100, null=True)),
                ("student_group_id", models.IntegerField(null=True)),
                ("total_enrollment", models.IntegerField(null=True)),
                ("total_tested", models.IntegerField(null=True)),
                ("total_tested_with_scores", models.IntegerField(null=True)),
                ("total_enrollment_with_scores", models.IntegerField(null=True)),
                ("mean_scale_score", models.FloatField(null=True)),
                ("percentage_met_above", models.FloatField(null=True)),
                ("count_met_above", models.IntegerField(null=True)),
                ("percentage_nearly_met", models.FloatField(null=True)),
                ("count_nearly_met", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MathTestScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("county_code", models.IntegerField(null=True)),
                ("district_code", models.IntegerField(null=True)),
                ("district_name", models.CharField(max_length=100, null=True)),
                ("school_code", models.IntegerField(null=True)),
                ("school_name", models.CharField(max_length=100, null=True)),
                ("student_group_id", models.IntegerField(null=True)),
                ("total_enrollment", models.IntegerField(null=True)),
                ("total_tested", models.IntegerField(null=True)),
                ("total_tested_with_scores", models.IntegerField(null=True)),
                ("total_enrollment_with_scores", models.IntegerField(null=True)),
                ("mean_scale_score", models.FloatField(null=True)),
                ("percentage_met_above", models.FloatField(null=True)),
                ("count_met_above", models.IntegerField(null=True)),
                ("percentage_nearly_met", models.FloatField(null=True)),
                ("count_nearly_met", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Salary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("salary", models.FloatField(null=True)),
                ("employee_name", models.CharField(max_length=100, null=True)),
                ("job_title", models.CharField(max_length=1000, null=True)),
                ("county", models.CharField(max_length=50, null=True)),
                ("entity", models.CharField(max_length=100, null=True)),
                ("year", models.IntegerField(null=True)),
                ("regular_pay", models.FloatField(null=True)),
                ("overtime_pay", models.FloatField(null=True)),
                ("other_pay", models.FloatField(null=True)),
                ("total_pay", models.FloatField(null=True)),
                ("benefits", models.FloatField(null=True)),
                ("total_pay_and_benefits", models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SchoolDistrict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("county", models.CharField(max_length=100)),
                ("district_name", models.CharField(max_length=100)),
                ("grade_low", models.CharField(max_length=50)),
                ("grade_high", models.CharField(max_length=50)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScienceTestScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("county_code", models.IntegerField(null=True)),
                ("district_code", models.IntegerField(null=True)),
                ("district_name", models.CharField(max_length=100, null=True)),
                ("school_code", models.IntegerField(null=True)),
                ("school_name", models.CharField(max_length=100, null=True)),
                ("student_group_id", models.IntegerField(null=True)),
                ("total_enrollment", models.IntegerField(null=True)),
                ("total_tested", models.IntegerField(null=True)),
                ("total_tested_with_scores", models.IntegerField(null=True)),
                ("total_enrollment_with_scores", models.IntegerField(null=True)),
                ("mean_scale_score", models.FloatField(null=True)),
                ("percentage_met_above", models.FloatField(null=True)),
                ("count_met_above", models.IntegerField(null=True)),
                ("percentage_nearly_met", models.FloatField(null=True)),
                ("count_nearly_met", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="StudentGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("demographic_id", models.IntegerField()),
                ("demographic_name", models.CharField(max_length=100)),
            ],
        ),
    ]
