# Generated by Django 6.0.5 on 2026-05-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CalEd", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Salary2021",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("salary", models.FloatField(null=True)),
                ("employee_name", models.CharField(max_length=100, null=True)),
                ("job_title", models.CharField(max_length=1000, null=True)),
                ("county", models.CharField(max_length=50, null=True)),
                ("entity", models.CharField(max_length=100, null=True)),
                ("year", models.IntegerField(null=True)),
                ("regular_pay", models.FloatField(null=True)),
                ("overtime_pay", models.FloatField(null=True)),
                ("other_pay", models.FloatField(null=True)),
                ("total_pay", models.FloatField(null=True)),
                ("benefits", models.FloatField(null=True)),
                ("total_pay_and_benefits", models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Salary2022",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("salary", models.FloatField(null=True)),
                ("employee_name", models.CharField(max_length=100, null=True)),
                ("job_title", models.CharField(max_length=1000, null=True)),
                ("county", models.CharField(max_length=50, null=True)),
                ("entity", models.CharField(max_length=100, null=True)),
                ("year", models.IntegerField(null=True)),
                ("regular_pay", models.FloatField(null=True)),
                ("overtime_pay", models.FloatField(null=True)),
                ("other_pay", models.FloatField(null=True)),
                ("total_pay", models.FloatField(null=True)),
                ("benefits", models.FloatField(null=True)),
                ("total_pay_and_benefits", models.FloatField(null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name="Salary",
            new_name="Salary2023",
        ),
    ]
