# Generated by Django 6.0.5 on 2026-05-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CalEd", "0002_salary2021_salary2022_rename_salary_salary2023"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvgByCounty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("county", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("regular_pay", models.FloatField(null=True)),
                ("overtime_pay", models.FloatField(null=True)),
                ("other_pay", models.FloatField(null=True)),
                ("total_pay", models.FloatField(null=True)),
                ("benefits", models.FloatField(null=True)),
                ("total_pay_and_benefits", models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AvgByDistrict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("district", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("regular_pay", models.FloatField(null=True)),
                ("overtime_pay", models.FloatField(null=True)),
                ("other_pay", models.FloatField(null=True)),
                ("total_pay", models.FloatField(null=True)),
                ("benefits", models.FloatField(null=True)),
                ("total_pay_and_benefits", models.FloatField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Salary2021",
        ),
        migrations.DeleteModel(
            name="Salary2022",
        ),
        migrations.DeleteModel(
            name="Salary2023",
        ),
    ]
