# Generated by Django 6.0.5 on 2026-05-27 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CalEd", "0003_avgbycounty_avgbydistrict_delete_salary2021_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="avgbydistrict",
            old_name="district",
            new_name="entity",
        ),
    ]
