# Generated by Django 6.0.5 on 2026-06-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CalEd", "0004_rename_district_avgbydistrict_entity"),
    ]

    operations = [
        migrations.CreateModel(
            name="AggByCounty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("county", models.CharField(max_length=100)),
                ("year", models.IntegerField(null=True)),
                ("regular_pay_min", models.FloatField(null=True)),
                ("regular_pay_max", models.FloatField(null=True)),
                ("regular_pay_avg", models.FloatField(null=True)),
                ("overtime_pay_min", models.FloatField(null=True)),
                ("overtime_pay_max", models.FloatField(null=True)),
                ("overtime_pay_avg", models.FloatField(null=True)),
                ("other_pay_min", models.FloatField(null=True)),
                ("other_pay_max", models.FloatField(null=True)),
                ("other_pay_avg", models.FloatField(null=True)),
                ("total_pay", models.FloatField(null=True)),
                ("total_pay_min", models.FloatField(null=True)),
                ("total_pay_max", models.FloatField(null=True)),
                ("total_pay_avg", models.FloatField(null=True)),
                ("benefits", models.FloatField(null=True)),
                ("benefits_min", models.FloatField(null=True)),
                ("benefits_max", models.FloatField(null=True)),
                ("benefits_avg", models.FloatField(null=True)),
                ("total_pay_and_benefits", models.FloatField(null=True)),
                ("total_pay_and_benefits_min", models.FloatField(null=True)),
                ("total_pay_and_benefits_max", models.FloatField(null=True)),
                ("total_pay_and_benefits_avg", models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AggByDistrict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("county", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("year", models.IntegerField(null=True)),
                ("regular_pay_min", models.FloatField(null=True)),
                ("regular_pay_max", models.FloatField(null=True)),
                ("regular_pay_mean", models.FloatField(null=True)),
                ("regular_pay_sum", models.FloatField(null=True)),
                ("overtime_pay_min", models.FloatField(null=True)),
                ("overtime_pay_max", models.FloatField(null=True)),
                ("overtime_pay_mean", models.FloatField(null=True)),
                ("overtime_pay_sum", models.FloatField(null=True)),
                ("other_pay_min", models.FloatField(null=True)),
                ("other_pay_max", models.FloatField(null=True)),
                ("other_pay_mean", models.FloatField(null=True)),
                ("other_pay_sum", models.FloatField(null=True)),
                ("total_pay_min", models.FloatField(null=True)),
                ("total_pay_max", models.FloatField(null=True)),
                ("total_pay_mean", models.FloatField(null=True)),
                ("total_pay_sum", models.FloatField(null=True)),
                ("benefits_min", models.FloatField(null=True)),
                ("benefits_max", models.FloatField(null=True)),
                ("benefits_mean", models.FloatField(null=True)),
                ("benefits_sum", models.FloatField(null=True)),
                ("total_pay_and_benefits_min", models.FloatField(null=True)),
                ("total_pay_and_benefits_max", models.FloatField(null=True)),
                ("total_pay_and_benefits_mean", models.FloatField(null=True)),
                ("total_pay_and_benefits_sum", models.FloatField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="AvgByCounty",
        ),
        migrations.DeleteModel(
            name="AvgByDistrict",
        ),
        migrations.DeleteModel(
            name="ELATestScore",
        ),
        migrations.DeleteModel(
            name="MathTestScore",
        ),
        migrations.RemoveField(
            model_name="elamathtestscore",
            name="count_met_above",
        ),
        migrations.RemoveField(
            model_name="elamathtestscore",
            name="count_nearly_met",
        ),
        migrations.RemoveField(
            model_name="elamathtestscore",
            name="total_enrollment_with_scores",
        ),
        migrations.RemoveField(
            model_name="sciencetestscore",
            name="count_met_above",
        ),
        migrations.RemoveField(
            model_name="sciencetestscore",
            name="count_nearly_met",
        ),
        migrations.RemoveField(
            model_name="sciencetestscore",
            name="total_enrollment_with_scores",
        ),
        migrations.AddField(
            model_name="elamathtestscore",
            name="county_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="elamathtestscore",
            name="grade",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="elamathtestscore",
            name="school_year",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="elamathtestscore",
            name="student_group_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="elamathtestscore",
            name="test_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="elamathtestscore",
            name="test_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sciencetestscore",
            name="county_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="sciencetestscore",
            name="grade",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="sciencetestscore",
            name="school_year",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="sciencetestscore",
            name="student_group_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sciencetestscore",
            name="test_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="sciencetestscore",
            name="test_name",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
