# Generated by Django 6.0.5 on 2026-06-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CalEd", "0005_aggbycounty_aggbydistrict_delete_avgbycounty_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elamathtestscore",
            name="school_year",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="sciencetestscore",
            name="school_year",
            field=models.CharField(null=True),
        ),
    ]
