# Generated by Django 6.0.5 on 2026-06-09 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CalEd", "0006_alter_elamathtestscore_school_year_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aggbycounty",
            old_name="benefits_avg",
            new_name="benefits_mean",
        ),
        migrations.RenameField(
            model_name="aggbycounty",
            old_name="other_pay_avg",
            new_name="other_pay_mean",
        ),
        migrations.RenameField(
            model_name="aggbycounty",
            old_name="overtime_pay_avg",
            new_name="overtime_pay_mean",
        ),
        migrations.RenameField(
            model_name="aggbycounty",
            old_name="regular_pay_avg",
            new_name="regular_pay_mean",
        ),
        migrations.RenameField(
            model_name="aggbycounty",
            old_name="total_pay_and_benefits_avg",
            new_name="total_pay_and_benefits_mean",
        ),
        migrations.RenameField(
            model_name="aggbycounty",
            old_name="total_pay_avg",
            new_name="total_pay_mean",
        ),
    ]
