# Generated by Django 6.0.5 on 2026-06-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CalEd", "0007_rename_benefits_avg_aggbycounty_benefits_mean_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aggbycounty",
            name="benefits",
        ),
        migrations.RemoveField(
            model_name="aggbycounty",
            name="total_pay",
        ),
        migrations.RemoveField(
            model_name="aggbycounty",
            name="total_pay_and_benefits",
        ),
        migrations.AddField(
            model_name="aggbycounty",
            name="benefits_sum",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="aggbycounty",
            name="other_pay_sum",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="aggbycounty",
            name="overtime_pay_sum",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="aggbycounty",
            name="regular_pay_sum",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="aggbycounty",
            name="total_pay_and_benefits_sum",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="aggbycounty",
            name="total_pay_sum",
            field=models.FloatField(null=True),
        ),
    ]
