# Generated by Django 6.0.5 on 2026-06-11 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CalEd", "0009_aggbycountya_aggbycountys_aggbycountyt_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="elamathtestscore",
            old_name="school_year",
            new_name="year",
        ),
        migrations.RenameField(
            model_name="sciencetestscore",
            old_name="school_year",
            new_name="year",
        ),
    ]
