# Generated by Django 6.0.5 on 2026-06-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CalEd", "0010_rename_school_year_elamathtestscore_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elamathtestscore",
            name="year",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="sciencetestscore",
            name="year",
            field=models.IntegerField(null=True),
        ),
    ]
